### ISSUE TITLE
allow to generate cnonce by callback function or change method of cnonce generation

### ISSUE THREAD

**Issue by bakanov** [jhthorsen/mojo-useragent-digestauth#1]
Hello, 
I have tested your plugin to authenticate on ZTE wifi router (ZXHN H118N).  I knpw that this device may be bad and not working according to digest authentication standard, but it don't allow me to authenticate with cnonce generated by this plugin. I can authenticate using LWP or Mozilla Firefox. 

When I change cnonce like that, I can authenticate:
sub _generate_nonce {
  return "0e163838ccd62299";
}

When I use old style cnonce,  I can't:
sub _generate_nonce {
  return "MTQyOTUzODc2MiAxYTVkNjdmMTI3MGI0ZjJiMjdkMzc5MjJhNGIwMDllYTk0M2JhYWIyIA";
}
(When I use this function without changes, I can't authenticate)

Thanks,
Dmitry

**Comment by jhthorsen** [comment]
Hi. I've experience the same issue, though I don't understand why it happens. I wonder why curl/firefox/other browsers manage to produce a nonce that works, while this module fail.

Anyway... Could you have a look at e45d3fc, and tell me if that could work for you?

**Comment by bakanov** [comment]
yes, it works now with:
my $tx = $ua->$_request_with_digest_auth('GET', $url, { "D-Client-Nonce" => "0e163838ccd62299" });

Thanks!

**Comment by jhthorsen** [comment]
OK. Cool. 0.03 is soon available on CPAN.

https://twitter.com/cpan_new/status/606019226344636416
